---
version: '3.3'
services:
  graphical-trcrt:
    build:
      dockerfile: Dockerfile
      context: .
    image: graphical-traceroute:latest
    # env_file:
    #   - ./env
    ports:
      - 8100:8100
      - 8180:80
    hostname: graphical-traceroute
