openapi: 3.0.0
info:
  description: Graphical Traceroute Backend API
  version: "1.0.0"
  title: Graphical Traceroute
paths:
  /traceroute:
    get:
      summary: obtains traceroutes from prometheus
      operationId: app.get_traceroutes
      description: |
        By passing in source, destination, time frame obtain an array of 
        traceroutes for the frontend to graph
      parameters:
        - in: query
          name: src
          description: source hostname performing the traceroute
          required: true
          schema:
            type: string
            example: localhost:9427
        - in: query
          name: dest
          description: destination hostname for the traceroute
          schema:
            type: string
            example: 1.1.1.1
        - in: query
          name: search_duration
          description: "duration of the search, relative to start_dt (searches backwards: start_dt - search_duration)"
          schema:
            type: string
            example: 2h
        - in: query
          name: start_dt
          description: start datetime for filtering traceroutes
          schema:
            type: string
            format: date-time
            example: '2016-08-29 09:12:33'
        - in: query
          name: num_tracert
          description: number of traceroutes to return in the query 
          schema:
            type: integer
            example: 6
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TraceRoute'
        '400':
          description: bad input parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: error message
                    example: "Search duration time unit 'a' is not supported. The following units are supported: s, m, h, d"
        '404':
          description: no metrics found
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: error message
                    example: No metrics found within specified range
  /max-routes:
    get:
      summary: obtains max number of routes to graph in the frontend
      operationId: app.max_routes
      responses:
        '200':
          description: obtained value from backend
          content:
            application/json:
              schema:
                type: object
                properties:
                  max_routes:
                    type: integer
                    description: Maximum number of traceroutes to graph
                    example: 8
  /src:
    get:
      summary: obtains traceroutes source instance label from prometheus
      operationId: app.get_sources
      responses:
        '200':
          description: sources
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '404':
          description: no sources found
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: error message
                    example: No label values found for traceroute source
  /dest:
    get:
      summary: obtains traceroutes target label from prometheus
      operationId: app.get_destinations
      responses:
        '200':
          description: sources
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '404':
          description: no destinations found
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: error message
                    example: No label values found for traceroute destination
components:
  schemas:
    TraceRoute:
      type: object
      required:
        - hops
        - trace_time
      properties:
        hops:
          type: array
          items:
            $ref: '#/components/schemas/Hop'
        trace_time:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
    Hop:
      type: object
      required:
        - ttl
        - host
      properties:
        ttl:
          type: integer
          example: 4
        host:
          type: string
          example: 171.55.90.12